apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: davidfowl/featherweb:latest
          name: web
          env:
            - name: REDIS__CONNECTIONSTRING
              value: "$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)"
            - name: ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: web
